project_name: "IMU-Video-MMEA"
# Exemple de ce qu'il doit y avoir dans configs/config.yaml
dataset:
  root_dir: /kaggle/input/dataset-har/UESTC-MMEA-CL
preprocessing:
  imu:
    target_freq: 50
    window_size: 5
  video:
    target_fps: 25
    segment_duration: 5
    num_frames: 10
    img_size: [224, 224]

model:
  projection_dim: 256
  imu:
    seq_len: 250     # 5s * 50Hz
    patch_size: 16
    channels: 6
    embed_dim: 128
  video:
    num_frames: 10
    embed_dim: 768   # Pour ViT-B/16
    pretrained: True

training:
  batch_size: 32
  epochs: 50
  lr: 0.0001
  temperature: 0.07